TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += thorlabsfw102c.db
DATA += thorlabsfw102c.proto

#=======================================
include $(TOP)/configure/RULES
